### ISSUE TITLE
Default rviz configuration

### ISSUE THREAD

**Issue by tomlogan501** [gsilano/BebopS#16]
Hi,
Could you add a default rviz launch for some examples ?

**Comment by gsilano** [comment]
Yes of course. Please, feel free to open all PRs which you want. Later, I will check the compatibility with the ROS package and manage the merge.

Thanks for your work.

**Comment by gsilano** [comment]
Any update on this issue? If not, I will close it.

**Comment by tomlogan501** [comment]
#28
