### ISSUE TITLE
Robot_namespace and multirobot

### ISSUE THREAD

**Issue by tomlogan501** [gsilano/BebopS#17]
Hi,
I got some trouble to pop the bebop with a husky
It seems that the robot_namespace isn't taken in account, neither the tf_prefix.

Could you check by poping 2 bebops ?

Thanks

**Comment by tomlogan501** [comment]
I did find maybe a clue in multirotor_base.urdf.xacro : it add an imu_link and a default baselink
I will try by adding a namespace to it

**Comment by gsilano** [comment]
Yes, you are right. The `robot_namespace` is not considered. In fact, if you see the `task1_world.launch` topics are remapped. 

You can see how I organized the sensors in the `bebop.urdf.xacro` file to include the sonar sensor.
