### ISSUE TITLE
Where are the values from Table I and II derived from the reference paper?

### ISSUE THREAD

**Issue by Luke-A-F** [gsilano/BebopS#18]
I am trying to manipulate the values from the position control law in the reference paper and possibly change the virtual bound inputs, but I do not see anywhere in the reference paper where the values for Table I and Table II are derived. When I do the math for max propeller speed from Table I with equation 5, it does not equal 18.6N that is in Table II as a physical Ut constraint.

Where are the values from Table I and II derived from that are in the reference paper?

**Comment by gsilano** [comment]
As you can read from the README.md file, the software platform is an extract of the work carried out for the industrial challenge of the 26th Mediterranean Conference on Control and Automation (MED'18) in which we participated ([here the conference report](https://ieeexplore.ieee.org/document/8667511)). The values shown in Tables I and II come from the description of the challenge.

I hope this helps.

**Comment by Luke-A-F** [comment]
Hm. I could not find the description of the challenge values in the conference report or the website, but thank you anyway.

**Comment by gsilano** [comment]
No! The report describes the event and the challenge. I suggest you to send me an e-mail.
