### ISSUE TITLE
UAV can't move

### ISSUE THREAD

**Issue by golden-memory** [gsilano/BebopS#25]
excuse me, if i make some mistakes
![11](https://user-images.githubusercontent.com/50734162/88741516-75241f80-d172-11ea-8e6b-842d842b6f4f.png)

**Comment by gsilano** [comment]
This seems to be an old problem. Have you tried to see if there are similar problems like yours in the issue tracker? However, first of all, I would see if everything works by executing a few simple commands, e.g., `rqt` to have a node graph and `rostopic list` to see the list of available topics. Then, give me back with the results and I will try to help you in some way.

**Comment by golden-memory** [comment]
> This seems to be an old problem. Have you tried to see if there are similar problems like yours in the issue tracker? However, first of all, I would see if everything works by executing a few simple commands, e.g., `rqt` to have a node graph and `rostopic list` to see the list of available topics. Then, give me back with the results and I will try to help you in some way.

Thank a lot! My installation environment is Ubuntu 16.04 with ROS Kinetic and Gazebo 7
When executing `roslaunch bebop_simulator bebop_without_controller.launch`, it shows that
![1](https://user-images.githubusercontent.com/50734162/88802424-a423ab00-d1dd-11ea-9303-f1414255a904.png)
![2](https://user-images.githubusercontent.com/50734162/88802450-abe34f80-d1dd-11ea-87f8-beff110718e7.png)
--------------------------------------------------------------------------------------------------------------------------------------------------------
when executing `rqt_graph`, it shows that
![122](https://user-images.githubusercontent.com/50734162/88802606-e0570b80-d1dd-11ea-802c-beff681c47ce.png)
![123](https://user-images.githubusercontent.com/50734162/88802645-efd65480-d1dd-11ea-917a-79cdda2dafa5.png)
![666](https://user-images.githubusercontent.com/50734162/88802728-0bd9f600-d1de-11ea-90ef-9f4a328886f3.png)
--------------------------------------------------------------------------------------------------------------------------------------------------------
when executing `rostopic list`, it shows that
![555](https://user-images.githubusercontent.com/50734162/88803322-dd104f80-d1de-11ea-9e71-f1a8c9a6a73c.png)
--------------------------------------------------------------------------------------------------------------------------------------------------------
my problem is, when executing `rostopic pub /gazebo/command/motor_speed mav_msgs/Actuators '{angular_velocities: [1000, 1000, 1000, 1000]}'` , it occurs error
![777](https://user-images.githubusercontent.com/50734162/88805393-af78d580-d1e1-11ea-82f0-2003a34e1482.png)

**Comment by gsilano** [comment]
Ye, I got it. As you can see, there is something wrong with the Gazebo and/or ROS environment. For this reason, the propeller angular velocities command cannot be sent. I suggest taking a look at previous issues.  For example, this one: https://github.com/gsilano/BebopS/issues/23

**Comment by golden-memory** [comment]
> Ye, I got it. As you can see, there is something wrong with the Gazebo and/or ROS environment. For this reason, the propeller angular velocities command cannot be sent. I suggest taking a look at previous issues. For example, this one: #23

Oh, it seems a old question. Anyway, Thanks for your guidance. I will continue to pay attention to this issue. Besides, I found I can control the UAV by using the `waypoints.txt`, it's enough for me temporary.
