### ISSUE TITLE
SITL with QGC

### ISSUE THREAD

**Issue by a-tab-a** [gsilano/BebopS#31]
Hello, can BebopS be connected with QGC and control from QGC? With simulation open in Gazebo, and utilizing  mavlink_bridge is it possible to connect to QGC? Or it needs additional interface or plugin?

**Comment by gsilano** [comment]
I don't know if I understand what QGC stands for. However, if you want to control bebop with ROS, you have to use this package: [bebop_autonomy](https://github.com/AutonomyLab/bebop_autonomy).

**Comment by a-tab-a** [comment]
I meant QGroundcontrol station or say any mission planner. How do I connect QGroundcontrol with BebopS? Thanks

**Comment by gsilano** [comment]
I think this repository can help you to set up the environment: https://github.com/PX4/sitl_gazebo

<blockquote><img src="https://avatars2.githubusercontent.com/u/2096014?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/PX4/sitl_gazebo">PX4/sitl_gazebo</a></strong></div><div>Set of plugins, models and worlds to use with OSRF Gazebo Simulator in SITL and HITL. - PX4/sitl_gazebo</div></blockquote>
