### ISSUE TITLE
Custom Messages in Matlab

### ISSUE THREAD

**Issue by vvami** [gsilano/BebopS#33]
Hello there,

Creating the custom messages like mav_msgs/Actuators in Matlab is mentioned in the wiki page, but I had a question about it. I tried that method but it didn't work with me but maybe that's because I didn't fully understand some parts. 

What I did is as follows: First of all, I downloaded the two `rar` files and unzipped them in the location `C:\Users\my_username\OneDrive\Documents\MATLAB` so that in that location I have two folders (customMessages & jarFiles_MATLAB). 

Then I created the `txt` file `javaclasspath.txt` in `C:\Users\my_username\AppData\Roaming\MathWorks\MATLAB\R2019b` and filled it with:
```
C:\Users\my_username\OneDrive\Documents\MATLAB\customMessages\matlab_gen\jar\geometry_msgs-1.12.5.jar
C:\Users\my_username\OneDrive\Documents\MATLAB\customMessages\matlab_gen\jar\sensor_msgs-1.12.5.jar
C:\Users\my_username\OneDrive\Documents\MATLAB\customMessages\matlab_gen\jar\trajectory_msgs-1.12.5.jar
C:\Users\my_username\OneDrive\Documents\MATLAB\customMessages\matlab_gen\jar\mav_msgs-3.2.0.jar
```
Now the problem is that when I open matlab, it says in the command window:
```
Warning: Name is nonexistent or not a directory:
C:\Users\my_username\OneDrive\Documents\MATLAB\customMessages\matlab_gen\msggen
```
And when I run the command:
`addpath('C:\Users\my_username/OneDrive\Documents\MATLAB\customMessages\matlab_gen\msggen');`

I get this:
`Warning: Name is nonexistent or not a directory: C:\Users\my_username\OneDrive\Documents\MATLAB\customMessages\matlab_gen\msggen`

Should I do any changes to the `rar` files I've downloaded and their paths maybe? 

Thank you in advance.

**Comment by gsilano** [comment]
Mhmm. Have you checked these issues? https://github.com/gsilano/CrazyS/issues/16, https://github.com/gsilano/CrazyS/issues/18, and https://github.com/gsilano/CrazyS/issues/19. Although they are for CrazyS (another ROS package of mine), they may help you figure out what went wrong. If not, we will investigate the problem.
