### ISSUE TITLE
UAV can't move

### ISSUE THREAD

**Issue by ZiyanLI9764** [gsilano/BebopS#34]
Hi, sorry to bother. I can't use the command to make the UAV spin. I am new to ROS, excuse if I make any mistake. My installation environment is Ubuntu 18.04.5 LTS with ROS melodic and Gazebo 9. 
![Screenshot from 2020-10-21 17-39-18](https://user-images.githubusercontent.com/57477491/96697102-7b6b1600-13c6-11eb-8e59-0b7e642e7ff2.png)
![Screenshot from 2020-10-21 17-39-44](https://user-images.githubusercontent.com/57477491/96697143-87ef6e80-13c6-11eb-9d82-29d7e950514b.png)
![Screenshot from 2020-10-21 17-39-58](https://user-images.githubusercontent.com/57477491/96697156-8b82f580-13c6-11eb-8e4a-4d0fda1d3e46.png)

**Comment by gsilano** [comment]
This is similar to #32, #30, #25, #21, and #27. Please, try to follow the described suggestions (see the content of the issue) and give me back if the problem still persists.

**Comment by ZiyanLI9764** [comment]
> This is similar to #32, #30, #25, #21, and #27. Please, try to follow the described suggestions (see the content of the issue) and give me back if the problem still persists.

Thanks very much for the reply. I checked them all and try to reinstall my environment follow your instruction. But the rotors still can't spin. I think it is quite similar to the #30, but I can only see this when I run the` roslaunch bebop_simulator bebop_without_controller.launch
` . Did I make any mistakes or miss any anything? I am really new to ROS, many thanks if you can give any guidance.
![rosgraph](https://user-images.githubusercontent.com/57477491/97006064-3f78b200-157a-11eb-852f-8d92ff74aa5a.png)

**Comment by gsilano** [comment]
Try to run this command `rostopic pub /command/motor_speed mav_msgs/Actuators '{angular_velocities: [1000, 1000, 1000, 1000]}`. Let me know if this fixes the issue.

**Comment by taminhtoan2601** [comment]
Hello, 

I fixed problem of rotors spin by adding <remap from="command/motor_speed" to="$(arg name)/command/motors" /> in the node "position_controller_node" (after line 84) in file task2_world.launch or task1_world also. After that, it worked.
![image](https://user-images.githubusercontent.com/58007568/98045351-a9ba0e00-1e28-11eb-9a3f-2b1e04b32b31.jpg)

**Comment by taminhtoan2601** [comment]
![Uploading image.jpg…]()

**Comment by gsilano** [comment]
Can I close this issue?

**Comment by ZiyanLI9764** [comment]
> Can I close this issue?

Yes! I tried taminhtoan's solution and everything is working fine right now. Thank you very much for your help.

**Comment by dkapur17** [comment]
@ZiyanLI9764, I'm facing the exact same issue that you were. Here is my `rqt_graph` when I run `roslaunch bebop_simulator bebop_without_controller.launch` and publish using `rostopic pub /command/motor_speed mav_msgs/Actuators '{angular_velocities: [1000, 1000, 1000, 1000]}'`:
![image](https://user-images.githubusercontent.com/37783178/135534694-d94309fd-f0cc-4822-b2ba-76e564feb386.png)

Everything seems to be executing fine, but the drone isn't taking off. I've gone through the links mentioned in this thread but haven't been able to figure out how to fix it. Could you let me know what made it work for you? Thanks!

(I'm using ROS Melodic with Gazebo 9, followed the setup instructions from the README).

**Comment by gsilano** [comment]
Hi @dkapur17! Have you tried reinstalling the package and creating the bashrc file? Have you also looked into the issues and steps outlined in this thread?
