### ISSUE TITLE
Running {task1_world_with_bebop,task2_world_with_bebop}.launch files

### ISSUE THREAD

**Issue by Nelson89** [gsilano/BebopS#36]
Hello,

I'm trying to run a task1_world_with_bebop.launch and task2_world_with_bebop.launch with command:
`$ roslaunch bebop_simulator task1_world_with_bebop.launch`. 

Unfortunately, problems arise when trying to run.
![bebopS_issue](https://user-images.githubusercontent.com/41027240/101645760-049de100-3a37-11eb-91cd-4c0bc9bc72ae.png)

I don't know why this error is showing up. If I try use other launch files, it works fine. I have tried with: gazebo_bebop.launch, bebop_without_controller.launch, task1_world.launch, task2_world.launch, task3_world.launch, multiple_bebop_without_controller.launch, multiple_task2_world.launch.

I use ROS Melodic on Ubuntu 18.04 with Gazebo 9.0.0

**Comment by gsilano** [comment]
Hi! The `with_bebop.launch` files consider the real Bebop in the loop. If you are only interested in simulating it, you can just run the standard version.

**Comment by Nelson89** [comment]
Hi,
Thank you for your answer! So if I understand correctly, this version `with_bebop.launch` is about a real drone in the real world and the other version is about a gazebo simulation?

**Comment by gsilano** [comment]
Yes, it is.

**Comment by Nelson89** [comment]
Ok, now I understand it.
Thank you!
