### ISSUE TITLE
root@7fe7b2744d5d:~/carla-ros-bridge/catkin_ws# sudo rosdep init

### ISSUE THREAD

**Issue by Raviteja-T** [gsilano/BebopS#38]
root@7fe7b2744d5d:~/carla-ros-bridge/catkin_ws# sudo rosdep init
ERROR: cannot download default sources list from:
https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/sources.list.d/20-default.list
Website may be down.

<blockquote></blockquote>

_Originally posted by @Raviteja-T in https://github.com/gsilano/BebopS/issues/3#issuecomment-743139028_

**Comment by gsilano** [comment]
This issue is not well written. Could you please provide further details? If not, I'll close it.

**Comment by Raviteja-T** [comment]
Tq
