### ISSUE TITLE
No motor spinning 

### ISSUE THREAD

**Issue by jocacace** [gsilano/BebopS#4]
Hi, 
I am trying to use the bebop simulator on my system. I tried both with a system based on ROS melodic (and hence Gazebo 9) and kinetic. The compilation works well but when I launch the task2_world.launch file the working scene is correctly loaded (the bebop is land) but the mission doesn't start. The rotors of the robot are completely hold. 

Do you have some suggestions to debug this problem?

Regards, 

Edit 1: 
I have tested the BebopS even with Ubuntu 16.04 and sadly the result is the same, no motor spinning

Edit 2:
Actually I checked the active topic after launched the bebop simulator, and the "/gazebo/command/motor_speed" is not listed.

**Comment by gsilano** [comment]
I'm investigating the issue, and I will give you back ASAP.

**Comment by jocacace** [comment]
Dear @gsilano 

Actually I found a problem with my setup. I have not switched on correct banch for rotors_simulator... so I think I am using different plugins to spawn the bebop robot...

**Comment by gsilano** [comment]
Nice. So, can I close the issue? Everything is fine?

**Comment by jocacace** [comment]
Yes, it works :)!

Thank you
