### ISSUE TITLE
Simulator not starting

### ISSUE THREAD

**Issue by ReDHaWk6520** [gsilano/BebopS#46]
Hello,

Thanks for this amazing work. I followed instructions step by step for Ubuntu 18.04 Ros Melodic Gazebo 9. I am not getting any errors on installing but when i try to manually fly or directly start task2_world, it opens Gazebo but the drone inside the simulation does nothing. From terminal i can see it is publishing waypoint but nothing happens. If you help me I would be very pleased.

**Comment by gsilano** [comment]
Hi! This is a common issues. I did not have time to investigate it. Try to follow the instructions in #34 or what reported at this link: https://github.com/gsilano/CrazyS/issues/40#issuecomment-942026373. I hope this helps.

**Comment by ReDHaWk6520** [comment]
Thank you for your quick response.  I will try them
