### ISSUE TITLE
drone simulation to live drone flight

### ISSUE THREAD

**Issue by Dk-0** [gsilano/BebopS#50]
The reality of bebop2 drone flight requires publishing the cmd_vel topic to the drone, and each piece of information under the topic is: linear.x and linear.y sections set the pitch and roll angles of the Bebop in degrees, respectively; linear.z controls the vertical speed of the Bebop in metres per second; angular.z controls the z controls the Bebop's vertical speed in metres per second; angular.z controls the Bebop's rotational speed (around the Z axis) in degrees per second. The details are shown in the figure below:
![2023-11-24 15:25:11](https://github.com/gsilano/BebopS/assets/72367129/df707fdd-a766-4d9a-b68e-4034ba30d2fc)

And there is no published topic for this in UAV simulation. All topics are shown below:
![2023-11-24 08:19:23](https://github.com/gsilano/BebopS/assets/72367129/30951129-370a-4272-8e16-4fb6fe0a5a17)

How should I control the real bebop2 drone to fly according to the simulation effect?

**Comment by gsilano** [comment]
Hi! Have you checked the `dev/bebopInterface` and `dev/sphinx` branches?

**Comment by Dk-0** [comment]
I did not check the dev/bebopInterface and dev/sphinx branches.
I just ran the command: roslaunch bebop_simulator multiple_task2_world.launch in the terminal and got all the topics below:
/bebop0/imu
/bebop0/joint_states
/bebop0/motor_speed
/bebop0/odometry
/bebop0/pose
/bebop0/pose_with_covariance
/bebop0/position
/bebop0/transform
/bebop1/imu
/bebop1/joint_states
/bebop1/motor_speed
/bebop1/odometry
/bebop1/pose
/bebop1/pose_with_covariance
/bebop1/position
/bebop1/transform
/bebop2/imu
/bebop2/joint_states
/bebop2/motor_speed
/bebop2/odometry
/bebop2/pose
/bebop2/pose_with_covariance
/bebop2/position
/bebop2/transform
/bebop3/imu
/bebop3/joint_states
/bebop3/motor_speed
/bebop3/odometry
/bebop3/pose
/bebop3/pose_with_covariance
/bebop3/position
/bebop3/transform
/bebop_0/bebop0/angularAndAngularVelocityErrors
/bebop_0/bebop0/camera1/camera_info
/bebop_0/bebop0/camera1/image_raw
/bebop_0/bebop0/camera1/image_raw/compressed
/bebop_0/bebop0/camera1/image_raw/compressed/parameter_descriptions
/bebop_0/bebop0/camera1/image_raw/compressed/parameter_updates
/bebop_0/bebop0/camera1/image_raw/compressedDepth
/bebop_0/bebop0/camera1/image_raw/compressedDepth/parameter_descriptions
/bebop_0/bebop0/camera1/image_raw/compressedDepth/parameter_updates
/bebop_0/bebop0/camera1/image_raw/theora
/bebop_0/bebop0/camera1/image_raw/theora/parameter_descriptions
/bebop_0/bebop0/camera1/image_raw/theora/parameter_updates
/bebop_0/bebop0/camera1/parameter_descriptions
/bebop_0/bebop0/camera1/parameter_updates
/bebop_0/bebop0/command/motors
/bebop_0/bebop0/command/trajectory
/bebop_0/bebop0/filteredOutput
/bebop_0/bebop0/motor_vel/0
/bebop_0/bebop0/motor_vel/1
/bebop_0/bebop0/motor_vel/2
/bebop_0/bebop0/motor_vel/3
/bebop_0/bebop0/odometry_gt
/bebop_0/bebop0/positionAndVelocityErrors
/bebop_0/bebop0/referenceAngles
/bebop_0/bebop0/smoothedTrajectory
/bebop_0/bebop0/stateErrors
/bebop_0/bebop0/uTerrComponents
/bebop_0/bebop0/zVelocityComponents
/bebop_0/wind_speed
/bebop_1/bebop1/angularAndAngularVelocityErrors
/bebop_1/bebop1/camera1/camera_info
/bebop_1/bebop1/camera1/image_raw
/bebop_1/bebop1/camera1/image_raw/compressed
/bebop_1/bebop1/camera1/image_raw/compressed/parameter_descriptions
/bebop_1/bebop1/camera1/image_raw/compressed/parameter_updates
/bebop_1/bebop1/camera1/image_raw/compressedDepth
/bebop_1/bebop1/camera1/image_raw/compressedDepth/parameter_descriptions
/bebop_1/bebop1/camera1/image_raw/compressedDepth/parameter_updates
/bebop_1/bebop1/camera1/image_raw/theora
/bebop_1/bebop1/camera1/image_raw/theora/parameter_descriptions
/bebop_1/bebop1/camera1/image_raw/theora/parameter_updates
/bebop_1/bebop1/camera1/parameter_descriptions
/bebop_1/bebop1/camera1/parameter_updates
/bebop_1/bebop1/command/motors
/bebop_1/bebop1/command/trajectory
/bebop_1/bebop1/filteredOutput
/bebop_1/bebop1/motor_vel/0
/bebop_1/bebop1/motor_vel/1
/bebop_1/bebop1/motor_vel/2
/bebop_1/bebop1/motor_vel/3
/bebop_1/bebop1/odometry_gt
/bebop_1/bebop1/positionAndVelocityErrors
/bebop_1/bebop1/referenceAngles
/bebop_1/bebop1/smoothedTrajectory
/bebop_1/bebop1/stateErrors
/bebop_1/bebop1/uTerrComponents
/bebop_1/bebop1/zVelocityComponents
/bebop_1/wind_speed
/bebop_2/bebop2/angularAndAngularVelocityErrors
/bebop_2/bebop2/camera1/camera_info
/bebop_2/bebop2/camera1/image_raw
/bebop_2/bebop2/camera1/image_raw/compressed
/bebop_2/bebop2/camera1/image_raw/compressed/parameter_descriptions
/bebop_2/bebop2/camera1/image_raw/compressed/parameter_updates
/bebop_2/bebop2/camera1/image_raw/compressedDepth
/bebop_2/bebop2/camera1/image_raw/compressedDepth/parameter_descriptions
/bebop_2/bebop2/camera1/image_raw/compressedDepth/parameter_updates
/bebop_2/bebop2/camera1/image_raw/theora
/bebop_2/bebop2/camera1/image_raw/theora/parameter_descriptions
/bebop_2/bebop2/camera1/image_raw/theora/parameter_updates
/bebop_2/bebop2/camera1/parameter_descriptions
/bebop_2/bebop2/camera1/parameter_updates
/bebop_2/bebop2/command/motors
/bebop_2/bebop2/command/trajectory
/bebop_2/bebop2/filteredOutput
/bebop_2/bebop2/motor_vel/0
/bebop_2/bebop2/motor_vel/1
/bebop_2/bebop2/motor_vel/2
/bebop_2/bebop2/motor_vel/3
/bebop_2/bebop2/odometry_gt
/bebop_2/bebop2/positionAndVelocityErrors
/bebop_2/bebop2/referenceAngles
/bebop_2/bebop2/smoothedTrajectory
/bebop_2/bebop2/stateErrors
/bebop_2/bebop2/uTerrComponents
/bebop_2/bebop2/zVelocityComponents
/bebop_2/wind_speed
/bebop_3/bebop3/angularAndAngularVelocityErrors
/bebop_3/bebop3/camera1/camera_info
/bebop_3/bebop3/camera1/image_raw
/bebop_3/bebop3/camera1/image_raw/compressed
/bebop_3/bebop3/camera1/image_raw/compressed/parameter_descriptions
/bebop_3/bebop3/camera1/image_raw/compressed/parameter_updates
/bebop_3/bebop3/camera1/image_raw/compressedDepth
/bebop_3/bebop3/camera1/image_raw/compressedDepth/parameter_descriptions
/bebop_3/bebop3/camera1/image_raw/compressedDepth/parameter_updates
/bebop_3/bebop3/camera1/image_raw/theora
/bebop_3/bebop3/camera1/image_raw/theora/parameter_descriptions
/bebop_3/bebop3/camera1/image_raw/theora/parameter_updates
/bebop_3/bebop3/camera1/parameter_descriptions
/bebop_3/bebop3/camera1/parameter_updates
/bebop_3/bebop3/command/motors
/bebop_3/bebop3/command/trajectory
/bebop_3/bebop3/filteredOutput
/bebop_3/bebop3/motor_vel/0
/bebop_3/bebop3/motor_vel/1
/bebop_3/bebop3/motor_vel/2
/bebop_3/bebop3/motor_vel/3
/bebop_3/bebop3/odometry_gt
/bebop_3/bebop3/positionAndVelocityErrors
/bebop_3/bebop3/referenceAngles
/bebop_3/bebop3/smoothedTrajectory
/bebop_3/bebop3/stateErrors
/bebop_3/bebop3/uTerrComponents
/bebop_3/bebop3/zVelocityComponents
/bebop_3/wind_speed
/clock
/gazebo/link_states
/gazebo/model_states
/gazebo/parameter_descriptions
/gazebo/parameter_updates
/gazebo/set_link_state
/gazebo/set_model_state
/rosout
/rosout_agg
/tf

What I understand is that in the simulation the drone publishes the cmd_vel topics, and in reality the drone needs to just subscribe to the cmd_vel topics and it will fly according to the effect in the simulation (just like the UGV).
Please forgive me, I'm a beginner in UAV, so I don't really know how to check dev/bebopInterface and dev/sphinx branches. Could you please provide some specific details on how to do that?

**Comment by gsilano** [comment]
Hello! Sorry for the delay. As I said in my previous comment, you should jump into the other branches. There, you will find scripts and interfaces that you are looking for. Sorry if I'm not helping you any further, but this is a very intensive period for me. I hope this helps.

**Comment by Dk-0** [comment]
Thank you so much for taking the time to respond to my issue. Your help has been greatly appreciated! Wishing you all the best with your research! Take care!
